### ISSUE TITLE
getting Exception when I use this library in class extended by Activity

### ISSUE THREAD

**Issue by shamoon192** [saeedsh92/Banner-Slider#47]
![issue](https://user-images.githubusercontent.com/20418797/34144940-481db0f0-e4ad-11e7-9713-40c9b2c9e103.png)

kindly fix this issue ASAP

**Comment by shamoon192** [comment]
fixed ... no need to pull any new code for that issue

**Comment by manafzar** [comment]
@shamoon192 how did you solved it because i have extended the activity from a class which is extended from AppCompatActivity but still getting this exception

**Comment by Merseyside** [comment]
The same problem. Trying to set it in not AppCompatActivity. Any ideas how to use it in not CompatActivity class?

**Comment by shamoon192** [comment]
extend your class from AppCompatActivity and give custom theme whose parent theme should be Theme.AppCompat.Light.NoActionBar
